import type { Metadata } from "next";
import "./globals.css";
import "../scss/main.scss";

import {Header} from '@/templates/header-footer/Header';
import {Footer} from "@/templates/header-footer/Footer";
import {Analytics} from "@vercel/analytics/next";

export const metadata: Metadata = {
  title: "LECH-SYSTEM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body>
          <Header />
          {children}
          <Footer />
          <Analytics />
      </body>
    </html>
  );
}
